Prueba Cambiando simulación a Docker 3

diff --git a/.github/workflows/ci-deploy.yml b/.github/workflows/ci-deploy.yml
--- a/.github/workflows/ci-deploy.yml
+++ b/.github/workflows/ci-deploy.yml
@@ -65,9 +65,14 @@ jobs:
       - name: Run Acceptance Tests
         run: |
           echo "Esperando que el contenedor arranque..."
-          sleep 15
+          sleep 10
           echo "Ejecutando pruebas contra Canary"
-          curl -f http://localhost:8080 || (docker logs examen-canary && exit 1)
+          if curl -s http://localhost:8081/ | grep "<html>"; then
+            echo "Tests OK"
+          else
+            echo "Tests fallaron, abortando despliegue"
+            exit 1
+          fi
 
       # ================================
       # STAGE: Deploy Green (simulado)
